name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Release]
        build_platform: [Any CPU]
        build_boost_version: [1_75_0]
        build_boost_version_dot: [1.75.0]
        build_msvc_version_dot: [14.2]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: restore input nuget packages
      working-directory: builder\
      run: |
           nuget restore builder\packages.config -PackagesDirectory packages
           nuget restore builderTest\packages.config -PackagesDirectory packages

    - name: Setup to add MSBuild.exe to path
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild of builder
      working-directory: builder\
      run: |
           msbuild builder.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"
           msbuild builder.sln /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"
      
    - name: boost download
      working-directory: .
      run: |
          Set-Location -Path 'D:\a'
          New-Item -ItemType directory -Path D:\a\boost
          Set-Location -Path 'D:\a\boost'
          (New-Object System.Net.WebClient).DownloadFile("https://dl.bintray.com/boostorg/release/${{ matrix.build_boost_version_dot }}/binaries/boost_${{ matrix.build_boost_version }}-bin-msvc-all-32-64.7z", "C:\Temp\boost_${{ matrix.build_boost_version }}-bin-msvc-all-32-64.7z")
          7z x -y C:\Temp\boost_${{ matrix.build_boost_version }}-bin-msvc-all-32-64.7z | Out-Null
          Rename-Item -Path ".\boost_${{ matrix.build_boost_version }}-bin-msvc-all-32-64.7z" -NewName "boost"


    - name: run builder
      working-directory: builder\builder\bin\Release\
      run: .\builder.exe
